server:
  port: 85
spring:
#  security:
#    user:
#      name: atwang
#      password: atwang
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springsecurity?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
mybatis-plus:
  mapper-locations: classpath:dao/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
